### ISSUE TITLE
🐛 "No time zone found with key" error in Windows 

### ISSUE THREAD

**Issue by xjhofernandes** [ericmiguel/timeless#4]
Hello, @ericmiguel !

When i tried to import the timeless module (in my windows enviroment), there's a exception with the message: 

```
No time zone found with key
```

So, i searched about this error and i found some issues with the python getting the local timezone from a Windows.

And one of the solutions was install (via pip) the tzdata lib. When i installed the "tzdata" via pip, the "No time zone found with key" error message has gone and the Timeless lib worked great!

Command:
```
pip install tzdata
```

GitHub topic about this issue: https://github.com/ecederstrand/exchangelib/issues/897

And the StackOverFlow question with the "tzdata" tip: https://stackoverflow.com/questions/71058888/zoneinfonotfounderror-no-time-zone-found-with-key-utc

Thank's for the lib. It's AMAAAZING! ❤️‍🔥

**Comment by ericmiguel** [comment]
@xjhofernandes version 0.2.0 now has Win32 support. Hope it attends your demand.
